- name: get helm-stable version
  uri:
    url: https://api.github.com/repos/helm/helm/releases/latest
  register: helm_stable

- set_fact:
    helm_stable: "{{helm_stable.json.tag_name}}"

- get_url:
    url: "https://get.helm.sh/helm-{{helm_stable}}-linux-amd64.tar.gz"
    dest: "{{tmpdir}}/helm.tar.gz"

- file:
    path: "{{tmpdir}}/helm"
    state: directory

- unarchive:
    src: "{{tmpdir}}/helm.tar.gz"
    dest: "{{tmpdir}}/helm"

- copy:
    src: "{{tmpdir}}/helm/linux-amd64/helm"
    dest: "{{bindir}}/helm"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: yes