- name: get kompose-stable version
  uri:
    url: https://api.github.com/repos/kubernetes/kompose/releases/latest
  register: kompose_stable

- set_fact:
    kompose_stable: "{{kompose_stable.json.tag_name}}"

- get_url:
    url: "https://github.com/kubernetes/kompose/releases/download/{{kompose_stable}}/kompose-linux-amd64"
    dest: "{{bindir}}/kompose"
  become: yes

- file:
    path: "{{bindir}}/kompose"
    mode: '0755'
  become: yes

- blockinfile:
    path: "{{bashrc}}"
    marker: "# {mark} ansible - kompose completion"
    block: source <(kompose completion bash)
