# https://api.github.com/repos/rancher/cli/releases/latest 
# https://github.com/rancher/cli/releases/download/v2.3.2/rancher-linux-amd64-v2.3.2.tar.gz 

- name: get rancher-stable version
  uri:
    url: https://api.github.com/repos/rancher/cli/releases/latest
  register: rancher_stable

- set_fact:
    rancher_stable: "{{rancher_stable.json.tag_name}}"

- get_url:
    url: "https://github.com/rancher/cli/releases/download/{{rancher_stable}}/rancher-linux-amd64-{{rancher_stable}}.tar.gz "
    dest: "{{tmpdir}}/rancher.tar.gz"

- file:
    path: "{{tmpdir}}/rancher"
    state: directory

- unarchive:
    src: "{{tmpdir}}/rancher.tar.gz"
    dest: "{{tmpdir}}/rancher"

- copy:
    src: "{{tmpdir}}/rancher/rancher-{{rancher_stable}}/rancher"
    dest: "{{bindir}}/rancher"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: yes